# Create a role biniding using the default ClusterRole: edit but confined to the specific namespace
# the Google cloud account needs to have Kubernetes Engine Cluster Viewer role to get kubectl to
# authenticatie with gcloud command. 
# the bottom comments show a list of kubectl command interactions as the edit ClusterRole
# to get a list of ClusterRoles: kubectl get clusterroles
# To use a Google group, refer to https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#google-groups-for-gke

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-binding
  namespace: default
subjects:
# GCP user account
- kind: User
  name: user@domain.com
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io


# $ kubectl get pods
# No resources found.
# $ kubectl create namespace n1
# Error from server (Forbidden): namespaces is forbidden: User "user@domain.com" cannot create resource "namespaces" in API group "" at the cluster scope: Required "container.namespaces.create" permission.
# $ kubectl create deployment nginx --image=nginx
# deployment.apps/nginx created
# $ kubectl get deployments
# NAME    READY   UP-TO-DATE   AVAILABLE   AGE
# nginx   0/1     1            0           11s
