steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gsakeymanager', './cloudrun/gsakey']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gsakeymanager']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'gsakeymanager', '--image', 'gcr.io/$PROJECT_ID/gsakeymanager', '--region', 'us-central1', '--platform', 'managed', '--service-account', 'gke-test@tcsplayground.iam.gserviceaccount.com', '--no-allow-unauthenticated', '--memory', '512M']
images:
- gcr.io/$PROJECT_ID/gsakeymanager
