steps:
  - name: 'gcr.io/cloud-builders/curl'
    entrypoint: 'bash'
    args:
      - '-c' # pass what follows as a command to bash
      - |
        cp -v gcp-compute/delete-expired.py ./main.py
        cp -v gcp-compute/requirements.txt ./
  - name: gcr.io/cloud-builders/gcloud
    args: ['functions', 'deploy', 'delete_expired_gce', '--entry-point', 'main', '--runtime', 'python37', '--trigger-topic', 'delete-expired-gce']