apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: web-volume
        ports:
        - containerPort: 80
      volumes:
      - name: web-volume
        gcePersistentDisk:
          pdName: web-resources
          fsType: ext4
          readOnly: true