steps:
# deploy cloud function to call Cloud Run GSA key manager service
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      git clone https://github.com/hilliao/enterprise-solutions.git && cd cloudrun/gsakey/client && \
      gcloud functions deploy gsakeymanager-beta --runtime python38 --trigger-topic $_TOPIC \
      --entry-point process_key --set-env-vars CLOUD_RUN_URL=$_CLOUD_RUN_URL \
      --service-account=$_GCP_SA
