# gcloud deployment-manager deployments create tmp-hil-test-1 --config gsakey.yaml --preview

imports:
- path: gsakey.py

resources:
#- name: create-sa
#  type: iam.v1.serviceAccount
#  properties:
#    displayName: 'testing creating SA from deployment manager'
#    accountId: hil-tmp-accountid-sa1
#    accessControl:

- name: gsakey
  type: gsakey.py
  properties:
    svc_googleapis_com: dialogflow
    service-account: hil-tmp-sa1
    role: roles/dataflow.admin

# TODO: Grant Project_number@cloudbuild.gserviceaccount.com Cloud Run Admin role